### ISSUE TITLE
Is there any pre-trained model available?

### ISSUE THREAD

**Issue by MoyanZitto** [jordipons/pandora-auto-tagging-models#1]
Hi jordipons,
    Would you pls be so kind to upload the model you trained in the paper? In this case we could compare your model and the model trained by ourselves.

**Comment by urinieto** [comment]
Unfortunately, we are not allowed to share pre-trained models for now. This might change in the near future, though.

**Comment by saxenarohit** [comment]
Not even the network trained without private dataset?

**Comment by urinieto** [comment]
Not for now.

**Comment by jordipons** [comment]
Actually, I'm now working on a version of the code that it will be fully open-sourced. I plan to also share a neural network trained with the Million Song Dataset. However, this will happen during the following months (not sure exactly when).

**Comment by jordipons** [comment]
Pre-trained models trained with the Million Song Dataset and the MagnaTagATune are now available at: https://github.com/jordipons/musicnn

Enjoy! :)
