### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by oplatek** [jordipons/pandora-auto-tagging-models#2]
Hi!

Thank you for the open-source implementation of your article (and a very interesting article).
Can you pls add a license?

An MIT or Apache 2.0 would be great but it is obviously up to you ;-)

Ondra

**Comment by urinieto** [comment]
Hi there,

Thanks for bringing this up. The code should be licensed under a BSD-3 license. I just created a PR to reflect the changes: https://github.com/jordipons/music-audio-tagging-at-scale-models/pull/3

Best,
oriol

**Comment by jordipons** [comment]
Great, thanks Uri!
