### ISSUE TITLE
Wrapper code to use model.py

### ISSUE THREAD

**Issue by joecheriross** [jordipons/pandora-auto-tagging-models#5]
Hi, 

  Do you have any wrapper code snippet to use model.py for training and testing ? Since I have not ever dealt with audio content before, I am not sure of what all preprocessing to be done before the data is passed to the placeholders. 
Checking in the code snippets for this will be very helpful.

**Comment by jordipons** [comment]
Yes! Now you have code to train and test all these models in https://github.com/jordipons/musicnn-training

Enjoy :)
